if (self.CavalryLogger) { CavalryLogger.start_js(["l+URG"]); }

__d("XCometCommerceProductItemControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f){a=b("jsRouteBuilder")("/commerce/products/{listing_id}/",Object.freeze({}),void 0);e.exports=a}),null);
__d("ProductTaggingBuyerTypedLogger",["Banzai","GeneratedLoggerUtils","nullthrows"],(function(a,b,c,d,e,f){"use strict";a=function(){function a(){this.$1={}}var c=a.prototype;c.log=function(a){b("GeneratedLoggerUtils").log("logger:ProductTaggingBuyerLoggerConfig",this.$1,b("Banzai").BASIC,a)};c.logVital=function(a){b("GeneratedLoggerUtils").log("logger:ProductTaggingBuyerLoggerConfig",this.$1,b("Banzai").VITAL,a)};c.logImmediately=function(a){b("GeneratedLoggerUtils").log("logger:ProductTaggingBuyerLoggerConfig",this.$1,{signal:!0},a)};c.clear=function(){this.$1={};return this};c.getData=function(){return babelHelpers["extends"]({},this.$1)};c.updateData=function(a){this.$1=babelHelpers["extends"]({},this.$1,a);return this};c.setAdID=function(a){this.$1.ad_id=a;return this};c.setClientTime=function(a){this.$1.client_time=a;return this};c.setComponent=function(a){this.$1.component=a;return this};c.setCreatorID=function(a){this.$1.creator_id=a;return this};c.setDurationMs=function(a){this.$1.duration_ms=a;return this};c.setFunnelID=function(a){this.$1.funnel_id=a;return this};c.setIndex=function(a){this.$1.index=a;return this};c.setLogID=function(a){this.$1.log_id=a;return this};c.setObjectID=function(a){this.$1.object_id=a;return this};c.setParentLogID=function(a){this.$1.parent_log_id=a;return this};c.setPostID=function(a){this.$1.post_id=a;return this};c.setProductItemID=function(a){this.$1.product_item_id=a;return this};c.setReferralCode=function(a){this.$1.referral_code=a;return this};c.setSellerCurrency=function(a){this.$1.seller_currency=a;return this};c.setSellerProfileID=function(a){this.$1.seller_profile_id=a;return this};c.setSessionID=function(a){this.$1.session_id=a;return this};c.setSurface=function(a){this.$1.surface=a;return this};c.setUnresolvedEvent=function(a){this.$1.unresolved_event=a;return this};c.setVideoViewDurationMs=function(a){this.$1.video_view_duration_ms=a;return this};return a}();c={ad_id:!0,client_time:!0,component:!0,creator_id:!0,duration_ms:!0,funnel_id:!0,index:!0,log_id:!0,object_id:!0,parent_log_id:!0,post_id:!0,product_item_id:!0,referral_code:!0,seller_currency:!0,seller_profile_id:!0,session_id:!0,surface:!0,unresolved_event:!0,video_view_duration_ms:!0};e.exports=a}),null);
__d("CometStoryAggregatedUsersSuffixDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3644368755651942",metadata:{relayPreloadable:!0},name:"CometStoryAggregatedUsersSuffixDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("useCometMediaURL_media.graphql",[],(function(a,b,c,d,e,f){"use strict";a=function(){var a={alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null};a=[a,{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"owner",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},a,{kind:"InlineFragment",selections:[{alias:null,args:null,kind:"ScalarField",name:"uri_token",storageKey:null}],type:"Page",abstractKey:null}],storageKey:null}];return{argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useCometMediaURL_media",selections:[{kind:"InlineDataFragmentSpread",name:"getCometMediaURL_media",selections:[{alias:null,args:null,kind:"ScalarField",name:"is_playable",storageKey:null},{kind:"InlineFragment",selections:a,type:"Photo",abstractKey:null},{kind:"InlineFragment",selections:a,type:"Video",abstractKey:null}]}],type:"Media",abstractKey:"__isMedia"}}();e.exports=a}),null);
__d("CometProductTagReferralCodeContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(null);e.exports=c}),null);
__d("CometStoryAggregatedUsersSuffixDialog.entrypoint",["JSResourceForInteraction","WebPixelRatio","CometStoryAggregatedUsersSuffixDialogQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){var c=a.storyID;a=a.storyRenderLocation;return{queries:{queryReference:{parameters:b("CometStoryAggregatedUsersSuffixDialogQuery$Parameters"),variables:{id:c,renderLocation:a,scale:b("WebPixelRatio").get()}}}}},root:b("JSResourceForInteraction")("CometStoryAggregatedUsersSuffixDialog.react",{"class":"responsive",name:"Comet Aggregated Users Suffix Dialog",oncall:"comet_feed"}).__setRef("CometStoryAggregatedUsersSuffixDialog.entrypoint")};e.exports=a}),null);
__d("useMediaViewerVPVDLogger",["CometInteractionSourceContext","React","WebSession","gkx","requireDeferred","useVPVDImpression"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React"),h=b("requireDeferred")("CometMediaVpvdFalcoEvent");function a(a,c){var d=g.useContext(b("CometInteractionSourceContext")),e=a.authorId,f=a.createdTime,i=a.fbid,j=a.source,k=a.storyContainerId;c=g.useCallback(function(a){var c,g;a.hiddenTime;var l=a.visibleDuration;a=a.visibleTime;if(i==null)return;c=(c=j)!=null?c:d;var m={a:(g=e)!=null?g:"",ct:(g=f)!=null?g:0,d:l,i:i,s:c,si:k,sid:b("WebSession").getId(),vst:a};h.onReady(function(a){a=a.log;return a(function(){return m})})},[e,f,i,d,j,k]);return b("useVPVDImpression")({onVPVDEnd:c})}}),null);
__d("CometFeedStorySuffixAggregatedUsersRenderer",["CometEntryPointDialogTrigger.react","CometLink.react","CometStoryAggregatedUsersSuffixDialog.entrypoint","React","recoverableViolation"],(function(a,b,c,d,e,f){"use strict";var g=b("React");a=function(a,c){return function(d){if(a==null||c==null){b("recoverableViolation")("story ID or render location were null when rendering aggregated users link in story title","comet_ui");return d}return g.jsx(b("CometEntryPointDialogTrigger.react"),{dialogEntryPoint:b("CometStoryAggregatedUsersSuffixDialog.entrypoint"),otherProps:{},preloadParams:{storyID:a,storyRenderLocation:c},children:function(a){return g.jsx(b("CometLink.react"),{onClick:a,children:d})}})}};e.exports=a}),null);
__d("CometFeedStoryDropdownMenuLoggerContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({nodeID:null});e.exports=c}),null);
__d("CometMediaViewerRightRailUFIGlimmer.react",["BaseGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){return g.jsxs("div",{className:"dati1w0a ihqw7lf3 hv4rvrfc discj3wi kwzhilbh j83agx80",children:[g.jsx(b("BaseGlimmer.react"),{className:"a12rg87m bsodd3zb mwvzfrdb kxcb68kb kgjeooe1 dwerhba3",index:1}),g.jsx(b("BaseGlimmer.react"),{className:"a12rg87m bsodd3zb mwvzfrdb kxcb68kb kgjeooe1 dwerhba3",index:2}),g.jsx(b("BaseGlimmer.react"),{className:"a12rg87m bsodd3zb mwvzfrdb kxcb68kb kgjeooe1 dwerhba3",index:3})]})}}),null);
__d("useCometMediaURL",["CometRelay","getCometMediaURL","useCometMediaURL_media.graphql"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g;function a(a,c){a=b("CometRelay").useFragment(g!==void 0?g:g=b("useCometMediaURL_media.graphql"),a);return b("getCometMediaURL")(a,c)}}),null);
__d("CommercePdpProductTagClickFalcoEvent",["FalcoLoggerInternal","getSamplingPolicyConfig_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getSamplingPolicyConfig_DO_NOT_USE")("falco","commerce_pdp_product_tag_click");c=b("FalcoLoggerInternal").create(a);e.exports=c}),null);
__d("LiveShoppingViewerFalcoEvent",["FalcoLoggerInternal","getSamplingPolicyConfig_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getSamplingPolicyConfig_DO_NOT_USE")("falco","live_shopping_viewer");c=b("FalcoLoggerInternal").create(a);e.exports=c}),null);
__d("PagesPermalinkImpressionFalcoEvent",["FalcoLoggerInternal","getSamplingPolicyConfig_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getSamplingPolicyConfig_DO_NOT_USE")("falco","pages_permalink_impression");c=b("FalcoLoggerInternal").create(a);e.exports=c}),null);